on: [push]

name: build

jobs:
  build_whitesource_with_java:
    name: Build whitesource with java 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with java
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 20/java 
        tags: whitesource whitesource:20 whitesource:20.2 whitesource:20.2.1
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_whitesource_with_node:
    name: Build whitesource with node 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with node
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 20/node 
        tags: whitesource:node whitesource:20-node whitesource:20.2-node whitesource:20.2.1-node
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
 
  build_whitesource_with_docker:
    name: Build whitesource with docker 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with docker
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 20/docker 
        tags: whitesource:docker whitesource:20-docker whitesource:20.2-docker whitesource:20.2.1-docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_whitesource_with_dotnetcore:
    name: Build whitesource with dotnetcore
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with dotnetcore
      uses: philips-software/docker-ci-scripts@v1.0.1
      with:
        dockerfile: 20/dotnetcore 
        tags: whitesource:dotnetcore whitesource:20-dotnetcore whitesource:20-dotnetcore-3 whitesource:20.2-dotnetcore whitesource:20.2-dotnetcore-3.0 whitesource:20.2.1-dotnetcore whitesource:20.2.1-dotnetcore-3.0.101
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
