on: [push]

name: build

jobs:
  build_whitesource_with_java:
    name: Build whitesource with java 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with java
      uses: philips-software/docker-ci-scripts@v2.2.1
      with:
        dockerfile: 20/java 
        image-name: whitesource
        tags: latest 20 20.5 20.5.2
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_whitesource_with_node:
    name: Build whitesource with node 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with node
      uses: philips-software/docker-ci-scripts@v2.2.1
      with:
        dockerfile: 20/node 
        image-name: whitesource
        tags: node 20-node 20.5-node 20.5.2-node
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
 
  build_whitesource_with_docker:
    name: Build whitesource with docker 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with docker
      uses: philips-software/docker-ci-scripts@v2.2.1
      with:
        dockerfile: 20/docker 
        image-name: whitesource
        tags: docker 20-docker 20.5-docker 20.5.2-docker
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software

  build_whitesource_with_dotnetcore:
    name: Build whitesource with dotnetcore
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build whitesource Docker Images with dotnetcore
      uses: philips-software/docker-ci-scripts@v2.2.1
      with:
        dockerfile: 20/dotnetcore 
        image-name: whitesource
        tags: dotnetcore 20-dotnetcore 20-dotnetcore-3 20.5-dotnetcore 20.5-dotnetcore-3.0 20.5.2-dotnetcore 20.5.2-dotnetcore-3.0.101
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: '${{ secrets.DOCKER_PASSWORD }}'
        DOCKER_ORGANIZATION: philipssoftware
        GITHUB_ORGANIZATION: philips-software
